apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: three-tier
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    protocol: TCP
  selector:
    app: spring-boot-app
